#!/usr/bin/env python
"""
debug timer: measure run times of code, display results
"""
import sys
from time import perf_counter
from datetime import datetime
from tabulate import tabulate

from .utils import isotime, sleep

class DebugTimer():
    '''
    Measure run times for lines of code and summarize results

    Arguments
    ----------
    title (str): title used for starting message ['DebugTimer']
    verbose (bool): whether to print at each event [False]
    precision (int): timing precision [4]
    with_mod_count (bool): whether to include module count in report [False]

    '''
    def __init__(self, title=None, verbose=False, precision=4,
                 with_mod_count=False):
        self.verbose = verbose
        if title is None:
            title = "DebugTimer"
        self.title = title
        self.precision = precision
        self.with_mod_count = with_mod_count
        self.clear(title=title)

    def clear(self, title=None):
        """clear/reset debugtimer, optionally setting
        the `title` for the next run.
        """
        self.data = []
        if title is None:
            title = self.title
        self.add(f'{title}: {isotime()}')

    def add(self, msg):
        "add message point to debugtimer"
        self.data.append((msg, len(sys.modules), perf_counter()))
        if self.verbose:
            print(msg)

    def get_report(self, precision=None, with_mod_count=None,
                 tablefmt='simple_outline'):
        """get tabular report of results

        Arguments
        ------------
        precision:  int, precision for timing results [4]
        with_mod_count: bool, whether to include number of imported modules [False]
        tablefmt:  tabular format style

        Notes
        ------
        the output is formatted using the `tabulate` module, and the
        `tablefmt` option can be any of the formatting options it supports.
        An incomplete list of options is:

             "plain", "simple", "simple_grid", "pretty", "psql", "grid",
             "fancy_grid", "rounded_grid", "heavy_grid", "mixed_grid",
             "double_grid", "outline", "simple_outline", "rounded_outline",
             "heavy_outline", "mixed_outline", "double_outline",
             "fancy_outline", "pipe", "github", "orgtbl", "rst",,
             "mediawiki", "html", "textile", "latex", "latex_raw",
             "latex_booktabs", "latex_longtable", "jira", "tsv".

        """
        prec = self.precision
        if precision is not None:
            prec = precision
        with_nmod= self.with_mod_count
        if with_mod_count is None:
            with_mod_count = self.with_mod_count
        m0, n0, t0 = self.data[0]
        tprev= t0
        header = ['Message','Delta Time', 'Total Time']
        row  = [m0, 0, 0]
        if with_mod_count:
            header.append('# Modules')
            row.append(n0)
        table = [row[:]]
        for m, n, t in self.data[1:]:
            tt, dt = t-t0, t-tprev
            row = [m, dt, tt, n] if with_mod_count else [m, dt, tt]
            table.append(row[:])
            tprev = t
        ffmt = f'.{prec}f'
        return tabulate(table, header, floatfmt=ffmt, tablefmt=tablefmt)

    def show(self, precision=None, with_mod_count=False,
             tablefmt='outline'):
        """print the table generated by `get_report`"""
        print(self.get_report(precision=precision,
                             with_mod_count=with_mod_count,
                             tablefmt=tablefmt))


def debugtimer(title='DebugTimer', with_mod_count=False,
               verbose=False, precision=3):
    '''debugtimer returns a DebugTimer object to measure the runtime of
    portions of code, and then write a simple report of the results.

    Arguments
    ----------
    title:      str, optional title message ['DebugTimer']
    precision:  int, precision for timing results [4]
    with_mod_count: bool, whether to include number of imported modules [False]
    verbose:    bool, whether to print() each message when entered [False]

    Returns
    --------
    DebugTimer object, with methods:

    -  clear(title=None)  : reset Timer
    -  add(message)       : record time, with message
    -  get_report(tablefmt=='simple_outline')  : return text of report
    -  show(tablefmt='simple_outline')  : print timer report


    Example
    --------
    >>> timer = debugtimer('timer testing', precision=4)
    >>> result = foo(x=100)
    >>> timer.add('ran function foo')
    >>> bar(result)
    >>> timer.add('ran bar')
    >>> timer.show()
    '''
    return DebugTimer(title=title, precision=precision,
                      with_mod_count=with_mod_count, verbose=verbose)
